### PR TITLE
Fixed issue with opening Settings. (DMM updated settings to be a span on the main page)

### PR DESCRIPTION
**Pull request by KRadd1221**
Fixed background task defaulting to 'n' for running background task.

Replaced webdriver with undetected_chromedriver to avoid Captcha.

Added configurable settings for enabling background task. (Defaults to user input still)

Added configurable option for refresh interval.

Updated README.

### CODE REVIEW

**Review by KRadd1221 — COMMENTED** [review]
Fixed background task defaulting to 'n' for running background task.

Replaced webdriver with undetected_chromedriver to avoid Captcha.

Added configurable settings for enabling background task. (Defaults to user input still)

Added configurable option for refresh interval.

Updated README.

**Comment by Woahai321** [comment]
Thank you for this! :) <3

I took most of all this, besides the UC.

I tried playing with it yesterday and couldn't get it to work for some reason with Docker.

Ended up going a different route.

Honestly, I'm not sure if the Cloudflare issue is that big as I have never seen it personally.

If I keep getting reports, I will look into this further.

I did go with manager though to avoid a path altogether.

I nit picked and am closing this.

Thanks again! 👍

**Comment by Woahai321** [comment]
@all-contributors please add @KRadd1221 for code and bug

**Comment by Woahai321** [comment]
@KRadd1221 if you make another pull for something small, or useless lol, I can merge it so you can be a proper contributor if you care at all 🤣

**Comment by KRadd1221** [comment]
haha no big deal, if I need to change something I will. I made those few changes to get something that works for me and just figured I'd share. Thanks for this though, it's a good alternative for me at the moment

**Comment by Woahai321** [comment]
@KRadd1221 Understood!

If you feel up to it, give this new release a shot and let me know if it works for you.

Thanks again! :)

**Pull request closed without merging**
